# Generated by Django 3.2.4 on 2021-06-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='contact_dates',
            new_name='contacts_date',
        ),
    ]
